apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - deploy.yaml
  - svc.yaml
  - ingress.yaml

# Example: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/springboot/base/kustomization.yaml
configMapGenerator:
  - name: application-configuration
#    behavior: merge
    files:
      - application.properties

